/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kesehatan
         * @description Kembalikan status hidup API beserta versi dan tanggal data panen.
         *
         *     Selalu membalas 200, termasuk ketika salinan data belum termuat di
         *     server. Dalam kondisi itu `versi_data` dan `tanggal_data` bernilai
         *     `null`, jadi keduanya sekaligus penanda kesiapan data.
         *
         *     `HEAD /health` juga dilayani, dengan badan respons dipotong.
         */
        get: operations["kesehatan_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/provinsi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Provinsi
         * @description Daftar seluruh provinsi yang dikenal API, berpaginasi.
         */
        get: operations["daftar_provinsi_api_wilayah_provinsi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/ringkasan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ringkasan Wilayah
         * @description Ringkasan jumlah provinsi, kabupaten, dan desa secara nasional.
         *
         *     Hasilnya satu objek, bukan daftar berpaginasi, sehingga jawabannya
         *     tidak menyertakan bagian meta.
         */
        get: operations["ringkasan_wilayah_api_wilayah_ringkasan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/pusat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pusat Wilayah
         * @description Titik pusat peta untuk setiap provinsi dan kabupaten.
         *
         *     Dipakai untuk memposisikan peta bertingkat dari tampilan nasional ke
         *     provinsi lalu ke kabupaten. Hasilnya satu objek, bukan daftar
         *     berpaginasi, sehingga jawabannya tidak menyertakan bagian meta.
         */
        get: operations["pusat_wilayah_api_wilayah_pusat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/kabupaten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Kabupaten
         * @description Daftar kabupaten, dengan filter opsional `prov` (kode provinsi 2 digit).
         *
         *     `prov` yang formatnya sah tapi kodenya tidak dikenal menghasilkan
         *     galat 404 dengan kode `WILAYAH_TIDAK_ADA`.
         */
        get: operations["daftar_kabupaten_api_wilayah_kabupaten_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/desa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Desa
         * @description Daftar desa dalam satu kabupaten. Parameter `kab` wajib diisi
         *     (kode kabupaten 4 digit).
         *
         *     `kab` yang formatnya sah tapi kodenya tidak dikenal menghasilkan
         *     galat 404 dengan kode `WILAYAH_TIDAK_ADA`.
         */
        get: operations["daftar_desa_api_wilayah_desa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desa/cari": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cari Desa
         * @description Cari desa lewat substring nama (`q`, tak peka kapital, minimal 2 huruf).
         *
         *     Peringkat: baris yang `nmdesa`-nya berawalan `q` ditempatkan di atas
         *     baris yang cuma mengandung `q`, seri diurutkan menaik lewat `iddesa`.
         *     Filter `kab` opsional menyaring hasil ke satu kabupaten. Baris yang
         *     dikembalikan adalah baris indeks kartu ekonomi utuh (sudah bawa
         *     `idkab`+`nmkab`).
         */
        get: operations["cari_desa_api_desa_cari_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/kartu/{iddesa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Kartu Ekonomi Desa
         * @description Kembalikan satu Kartu Ekonomi Desa utuh apa adanya: identitas,
         *     peta_peran, rekomendasi_aksi, potensi, kesiapan, biofisik, logistik,
         *     jalur_ekonomi, desa_kembar, fakta_program, dan mutu_data, tanpa
         *     penyaringan kolom maupun sisipan data lain.
         *
         *     `iddesa` yang tidak dikenal menghasilkan galat 404 dengan kode
         *     `DESA_TIDAK_ADA`.
         */
        get: operations["kartu_detail_api_model_kartu__iddesa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/peta-peran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Peta Peran
         * @description Daftar baris ringkas Peta Peran Desa dengan filter `prov`/`kab`/`zona`.
         *
         *     `zona` di luar nilai yang sah dijawab 422. `prov` dan `kab`, bila diisi,
         *     harus kode wilayah yang dikenal; kode yang tidak dikenal dijawab 404
         *     `WILAYAH_TIDAK_ADA`.
         */
        get: operations["daftar_peta_peran_api_model_peta_peran_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/peta-peran/ringkasan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ringkasan Peta Peran
         * @description Ringkasan Peta Peran per kabupaten: satu objek (`kab=`) atau daftar semua.
         *
         *     Tanpa `kab`, daftar seluruh kabupaten tetap dipaginasi dan mengisi
         *     `meta.total`. Dengan `kab`, satu objek dikembalikan tanpa `meta`. `kab`
         *     yang tidak dikenal dijawab 404 `WILAYAH_TIDAK_ADA`.
         */
        get: operations["ringkasan_peta_peran_api_model_peta_peran_ringkasan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/peta-peran/{iddesa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Peta Peran
         * @description Baris penuh Peta Peran Desa (42 kolom) apa adanya.
         *
         *     Kolom mutu data seperti `keyakinan`, `sumber_dominan`, dan
         *     `alasan_belum_terpetakan` tetap disertakan, tidak disaring. `iddesa`
         *     yang tidak dikenal dijawab 404 `DESA_TIDAK_ADA`.
         */
        get: operations["detail_peta_peran_api_model_peta_peran__iddesa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/citra-potensi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Sel Citra
         * @description Daftar sel citra potensi (metadata saja), filter opsional `prov`/`target`.
         */
        get: operations["daftar_sel_api_model_citra_potensi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/citra-potensi/sel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Sel Citra
         * @description Detail satu sel: metadata indeks digabung dengan `format_skor` dan `skor`.
         */
        get: operations["detail_sel_api_model_citra_potensi_sel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/jalur-ekonomi/{varian}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Jalur
         * @description Daftar baris ringkas jalur ekonomi, filter opsional `kab`/`iddesa`.
         */
        get: operations["daftar_jalur_api_model_jalur_ekonomi__varian__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/jalur-ekonomi/{varian}/{id_jalur}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Jalur
         * @description Detail satu grup jalur ekonomi utuh (apa adanya + `id_jalur`).
         */
        get: operations["detail_jalur_api_model_jalur_ekonomi__varian___id_jalur__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/desa-kembar/{iddesa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tetangga Desa Kembar
         * @description Kembalikan tetangga desa kembar terdekat untuk satu `iddesa`.
         *
         *     `iddesa` yang tidak dikenal di indeks kartu ekonomi dijawab 404
         *     `DESA_TIDAK_ADA`. Desa yang dikenal tetapi belum punya data kemiripan
         *     tetangga tetap dijawab 200, dengan `tetangga` kosong dan `keterangan`
         *     yang menjelaskan sebabnya.
         */
        get: operations["desa_kembar_api_model_desa_kembar__iddesa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berita/{iddesa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Berita Desa
         * @description Daftar Berita Desa satu desa, berpaginasi, urut tanggal terbit menurun.
         */
        get: operations["berita_desa_api_berita__iddesa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profil/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profil akun yang sedang masuk
         * @description Kembalikan id dan peran akun pemanggil, dibaca dari tabel `profil`.
         */
        get: operations["profil_saya_api_profil_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kirim Pesan
         * @description Jalankan satu giliran percakapan Asisten Desa.
         *
         *     Setiap permintaan mengirim ulang seluruh riwayat percakapan lewat
         *     `messages`; server tidak menyimpan riwayat apa pun. Jawaban selalu
         *     dikirim utuh dalam satu respons, bukan bertahap per token.
         *
         *     Ambang laju rute ini berlaku per pengguna, di atas ambang global per
         *     alamat IP yang berlaku untuk seluruh endpoint.
         *
         *     `meta` pada amplop selalu `null`. Jejak fungsi, model yang dipakai,
         *     cacah putaran alat, dan peringatan ada di dalam `data`.
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/berita/segarkan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Segarkan Berita
         * @description Mulai pekerjaan latar penyegaran RSS untuk daftar `iddesa` yang diminta.
         *
         *     Duplikat dibuang sambil mempertahankan urutan. `iddesa` pertama yang
         *     tidak dikenal di indeks kartu ekonomi menghentikan permintaan sebelum
         *     pekerjaan apa pun dimulai (404). Hanya satu pekerjaan boleh berjalan
         *     pada satu waktu. Permintaan kedua ditolak (409) selama pekerjaan lain
         *     masih berjalan. Pekerjaan sungguhan berjalan di latar; balasan ini hanya
         *     menandakan pekerjaan sudah dimulai (202), bukan sudah selesai.
         */
        post: operations["segarkan_berita_api_admin_berita_segarkan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/berita/{id_berita}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hapus Berita
         * @description Hapus satu berita lewat `id`; membalas 404 bila `id` tidak ada.
         */
        delete: operations["hapus_berita_api_admin_berita__id_berita__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pengguna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Pengguna
         * @description Daftar pengguna terdaftar beserta perannya, berpaginasi.
         *
         *     `q` menyaring berdasarkan email, tanpa peka kapital dan tanpa perlu cocok
         *     penuh. `meta.total` adalah cacah seluruh baris yang lolos saringan, bukan
         *     cacah baris pada halaman ini.
         */
        get: operations["daftar_pengguna_api_admin_pengguna_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pengguna/{id_pengguna}/peran": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ubah Peran
         * @description Ubah peran satu pengguna.
         *
         *     Mengubah peran diri sendiri lewat endpoint ini ditolak 403
         *     `AKSI_DITOLAK`. `id_pengguna` yang tidak terdaftar dijawab 404
         *     `PENGGUNA_TIDAK_ADA`.
         */
        post: operations["ubah_peran_api_admin_pengguna__id_pengguna__peran_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Sistem
         * @description Status sistem: versi data, cacah isi, pekerjaan latar, dan konfigurasi.
         *
         *     `konfigurasi` hanya berisi bendera boolean "sudah terisi atau belum" per
         *     layanan. Nilai kunci dan kredensial tidak pernah dikirim ke pemanggil.
         */
        get: operations["status_sistem_api_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/laporan/{iddesa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Laporan PDF Desa
         * @description PDF satu desa, gabungan Peta Peran dan Kartu Ekonomi.
         *
         *     Dibuat saat diminta, tanpa cache. `iddesa` yang tidak dikenal, tidak
         *     mempunyai data Kartu Ekonomi, atau tidak mempunyai baris Peta Peran,
         *     sama-sama dijawab 404 `DESA_TIDAK_ADA`.
         */
        get: operations["laporan_desa_api_laporan__iddesa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/desa/{idkab}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batas Desa Kabupaten
         * @description Sajikan berkas GeoJSON batas desa satu kabupaten, sudah terkompresi gzip.
         *
         *     `idkab` yang tidak dikenal menghasilkan galat 404 (amplop JSON) dengan
         *     kode `WILAYAH_TIDAK_ADA`. `idkab` dikenal tetapi berkas batas desa
         *     kabupaten itu belum tersedia menghasilkan galat 404 (amplop JSON)
         *     dengan kode `TIDAK_DITEMUKAN`. Respons yang berhasil membawa header
         *     `Content-Encoding: gzip` dan tidak memaksa unduh berkas.
         */
        get: operations["geo_desa_api_geo_desa__idkab__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Amplop[Any] */
        Amplop_Any_: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: unknown;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[BeritaTerhapus] */
        Amplop_BeritaTerhapus_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["BeritaTerhapus"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[DataDesaKembar] */
        Amplop_DataDesaKembar_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["DataDesaKembar"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[DataJawaban] */
        Amplop_DataJawaban_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["DataJawaban"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[DataKesehatan] */
        Amplop_DataKesehatan_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["DataKesehatan"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[DataStatus] */
        Amplop_DataStatus_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["DataStatus"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[PeranDiubah] */
        Amplop_PeranDiubah_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["PeranDiubah"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[ProfilSaya] */
        Amplop_ProfilSaya_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["ProfilSaya"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[PusatWilayah] */
        Amplop_PusatWilayah_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["PusatWilayah"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[RingkasanWilayah] */
        Amplop_RingkasanWilayah_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["RingkasanWilayah"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[TerimaSegarkan] */
        Amplop_TerimaSegarkan_: {
            /** Sukses */
            sukses: boolean;
            data?: components["schemas"]["TerimaSegarkan"] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[dict[str, Any]] */
        Amplop_dict_str__Any__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[BarisIndeksKartu]] */
        Amplop_list_BarisIndeksKartu__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["BarisIndeksKartu"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[DesaRingkas]] */
        Amplop_list_DesaRingkas__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["DesaRingkas"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[ItemBerita]] */
        Amplop_list_ItemBerita__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["ItemBerita"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[ItemPengguna]] */
        Amplop_list_ItemPengguna__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["ItemPengguna"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[Kabupaten]] */
        Amplop_list_Kabupaten__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["Kabupaten"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[Provinsi]] */
        Amplop_list_Provinsi__: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: components["schemas"]["Provinsi"][] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Amplop[list[dict[str, Any]]] */
        Amplop_list_dict_str__Any___: {
            /** Sukses */
            sukses: boolean;
            /** Data */
            data?: {
                [key: string]: unknown;
            }[] | null;
            galat?: components["schemas"]["Galat"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /**
         * BarisIndeksKartu
         * @description Baris indeks kartu ekonomi utuh: payload hasil pencarian desa.
         */
        BarisIndeksKartu: {
            /** Iddesa */
            iddesa: string;
            /** Nmdesa */
            nmdesa: string;
            /** Nmkec */
            nmkec: string;
            /** Idkab */
            idkab: string;
            /** Nmkab */
            nmkab: string;
            /** Zona */
            zona: string;
            /** Keyakinan */
            keyakinan: string;
            /** Potensi Dominan */
            potensi_dominan: string;
            /** Desil Sp */
            desil_sp: number;
            /** Desil Sk */
            desil_sk: number;
            /** N Program */
            n_program: number;
        };
        /** BeritaTerhapus */
        BeritaTerhapus: {
            /** Id */
            id: number;
            /** Terhapus */
            terhapus: boolean;
        };
        /** CacahSistem */
        CacahSistem: {
            /** Pengguna */
            pengguna: number;
            /** Berita */
            berita: number;
        };
        /**
         * DataDesaKembar
         * @description Payload data untuk `GET /api/model/desa-kembar/{iddesa}`.
         */
        DataDesaKembar: {
            /** Iddesa */
            iddesa: string;
            /** Tetangga */
            tetangga: components["schemas"]["TetanggaKembar"][];
            /** Keterangan */
            keterangan?: string | null;
        };
        /**
         * DataJawaban
         * @description Muatan `data` respons chat, termasuk jejak dan peringatan.
         */
        DataJawaban: {
            /** Jawaban */
            jawaban: string;
            /** Jejak Fungsi */
            jejak_fungsi: components["schemas"]["JejakFungsi"][];
            /** Model */
            model: string;
            /** Putaran Alat */
            putaran_alat: number;
            /** Peringatan */
            peringatan: string[];
        };
        /**
         * DataKesehatan
         * @description Payload data untuk endpoint `GET /health`.
         */
        DataKesehatan: {
            /** Status */
            status: string;
            /** Versi Data */
            versi_data: string | null;
            /** Tanggal Data */
            tanggal_data: string | null;
        };
        /** DataStatus */
        DataStatus: {
            /** Versi Data */
            versi_data: string | null;
            /** Tanggal Data */
            tanggal_data: string | null;
            cacah: components["schemas"]["CacahSistem"];
            penyegaran: components["schemas"]["StatusPekerjaan"] | null;
            /** Penyegaran Terakhir */
            penyegaran_terakhir: components["schemas"]["PenyegaranDesa"][];
            konfigurasi: components["schemas"]["KonfigurasiSiap"];
        };
        /**
         * DesaRingkas
         * @description Baris ringkas desa untuk daftar `GET /api/wilayah/desa`.
         */
        DesaRingkas: {
            /** Iddesa */
            iddesa: string;
            /** Nmdesa */
            nmdesa: string;
            /** Nmkec */
            nmkec: string;
        };
        /** Galat */
        Galat: {
            /** Kode */
            kode: string;
            /** Pesan */
            pesan: string;
        };
        /**
         * HasilPenyegaranDesa
         * @description Ringkasan satu desa dalam badan `/api/admin/status`.
         *
         *     `n_gagal` menghitung artikel yang gagal diproses karena galat, terpisah
         *     dari `n_dibuang` yang menghitung artikel yang ditolak saat penyaringan
         *     atau verifikasi editorial.
         */
        HasilPenyegaranDesa: {
            /** Iddesa */
            iddesa: string;
            /** N Baru */
            n_baru: number;
            /** N Duplikat */
            n_duplikat: number;
            /** N Dibuang */
            n_dibuang: number;
            /** N Gagal */
            n_gagal: number;
            /** Galat */
            galat: string | null;
        };
        /**
         * ItemBerita
         * @description Satu berita tersimpan; `perangkum` = gemini / ekstraktif / judul-rss.
         */
        ItemBerita: {
            /** Id */
            id: number;
            /** Judul */
            judul: string;
            /** Url */
            url: string;
            /** Sumber */
            sumber: string;
            /** Terbit Pada */
            terbit_pada: string | null;
            /**
             * Dipanen Pada
             * Format: date-time
             */
            dipanen_pada: string;
            /** Rangkuman */
            rangkuman: string | null;
            /** Kategori */
            kategori: string[];
            /** Perangkum */
            perangkum: string;
        };
        /** ItemPengguna */
        ItemPengguna: {
            /** Id */
            id: string;
            /** Email */
            email: string | null;
            /** Peran */
            peran: string;
            /**
             * Dibuat Pada
             * Format: date-time
             */
            dibuat_pada: string;
            /**
             * Diubah Pada
             * Format: date-time
             */
            diubah_pada: string;
        };
        /**
         * JejakFungsi
         * @description Satu pemanggilan fungsi yang benar-benar terjadi: jejak asal angka.
         */
        JejakFungsi: {
            /** Fungsi */
            fungsi: string;
            /** Argumen */
            argumen: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "sukses" | "gagal";
        };
        /**
         * Kabupaten
         * @description Satu baris kabupaten, berikut kode provinsi induknya.
         */
        Kabupaten: {
            /** Idkab */
            idkab: string;
            /** Nmkab */
            nmkab: string;
            /** Idprov */
            idprov: string;
        };
        /**
         * KonfigurasiSiap
         * @description Bendera boolean kesiapan konfigurasi untuk halaman `/admin`.
         *
         *     `gemini` menandai kunci API untuk panen Berita Desa, `gemini_chat`
         *     untuk Asisten Desa. Keduanya kunci terpisah, jadi satu bisa terisi
         *     sementara yang lain belum.
         */
        KonfigurasiSiap: {
            /** Supabase */
            supabase: boolean;
            /** Gemini */
            gemini: boolean;
            /** Gemini Chat */
            gemini_chat: boolean;
        };
        /** Meta */
        Meta: {
            /** Total */
            total: number;
            /** Hal */
            hal: number;
            /** Batas */
            batas: number;
            /** Parameter */
            parameter?: {
                [key: string]: unknown;
            } | null;
        };
        /** PenyegaranDesa */
        PenyegaranDesa: {
            /** Iddesa */
            iddesa: string;
            /**
             * Dipanen Pada
             * Format: date-time
             */
            dipanen_pada: string;
        };
        /**
         * PerProvinsiRingkasan
         * @description Rincian satu provinsi di dalam ringkasan wilayah.
         */
        PerProvinsiRingkasan: {
            /** Idprov */
            idprov: string;
            /** Nama */
            nama: string;
            /** N Kabupaten */
            n_kabupaten: number;
            /** N Desa */
            n_desa: number;
        };
        /** PeranDiubah */
        PeranDiubah: {
            /** Id */
            id: string;
            /** Peran */
            peran: string;
        };
        /**
         * PermintaanChat
         * @description Badan permintaan chat. Stateless: riwayat dikirim ulang tiap kali.
         */
        PermintaanChat: {
            /** Messages */
            messages: components["schemas"]["Pesan"][];
            /**
             * Temperature
             * @default 0.4
             */
            temperature: number;
        };
        /** PermintaanSegarkan */
        PermintaanSegarkan: {
            /** Iddesa */
            iddesa: string[];
        };
        /** PermintaanUbahPeran */
        PermintaanUbahPeran: {
            /**
             * Peran
             * @enum {string}
             */
            peran: "tamu" | "pemerintah" | "swasta" | "admin";
        };
        /**
         * Pesan
         * @description Satu giliran percakapan yang dikirim klien.
         *
         *     Peran "system" tidak diizinkan; hanya "user" dan "model" yang diterima.
         */
        Pesan: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "model";
            /** Isi */
            isi: string;
        };
        /**
         * ProfilSaya
         * @description Akun yang sedang masuk: id pengguna dan perannya.
         */
        ProfilSaya: {
            /** Id */
            id: string;
            /** Peran */
            peran: string;
        };
        /**
         * Provinsi
         * @description Satu baris provinsi: kode dan nama.
         */
        Provinsi: {
            /** Idprov */
            idprov: string;
            /** Nama */
            nama: string;
        };
        /**
         * PusatKabupaten
         * @description Pusat peta satu kabupaten + cacah desanya.
         */
        PusatKabupaten: {
            /** Idkab */
            idkab: string;
            /** Nmkab */
            nmkab: string;
            /** Idprov */
            idprov: string;
            /** Pusat */
            pusat: [
                number,
                number
            ];
            /** N Desa */
            n_desa: number;
        };
        /**
         * PusatProvinsi
         * @description Pusat peta satu provinsi (rerata kabupaten) + cacahnya.
         */
        PusatProvinsi: {
            /** Idprov */
            idprov: string;
            /** Nama */
            nama: string;
            /** Pusat */
            pusat: [
                number,
                number
            ];
            /** N Desa */
            n_desa: number;
            /** N Kabupaten */
            n_kabupaten: number;
        };
        /**
         * PusatWilayah
         * @description Payload `GET /api/wilayah/pusat`: titik pusat tiap provinsi dan
         *     kabupaten untuk kebutuhan tampilan peta.
         */
        PusatWilayah: {
            /** Provinsi */
            provinsi: components["schemas"]["PusatProvinsi"][];
            /** Kabupaten */
            kabupaten: components["schemas"]["PusatKabupaten"][];
        };
        /**
         * RingkasanWilayah
         * @description Payload `GET /api/wilayah/ringkasan`.
         */
        RingkasanWilayah: {
            /** N Provinsi */
            n_provinsi: number;
            /** N Kabupaten */
            n_kabupaten: number;
            /** N Desa */
            n_desa: number;
            /** Per Provinsi */
            per_provinsi: components["schemas"]["PerProvinsiRingkasan"][];
        };
        /** StatusPekerjaan */
        StatusPekerjaan: {
            /** Id Pekerjaan */
            id_pekerjaan: string;
            /**
             * Keadaan
             * @enum {string}
             */
            keadaan: "berjalan" | "selesai";
            /** Total */
            total: number;
            /** Selesai */
            selesai: number;
            /**
             * Mulai Pada
             * Format: date-time
             */
            mulai_pada: string;
            /** Selesai Pada */
            selesai_pada: string | null;
            /** Hasil */
            hasil: components["schemas"]["HasilPenyegaranDesa"][];
        };
        /** TerimaSegarkan */
        TerimaSegarkan: {
            /** Id Pekerjaan */
            id_pekerjaan: string;
            /** N Desa */
            n_desa: number;
            /** Keadaan */
            keadaan: string;
        };
        /**
         * TetanggaKembar
         * @description Satu desa tetangga dalam hasil desa kembar.
         *
         *     Identitas tetangga (`nmdesa`, `nmkec`, `idkab`, `nmkab`) diambil dari
         *     indeks kartu ekonomi. Bila `iddesa` tetangga tidak ada di sana, keempat
         *     field itu bernilai `null` sementara `persen` tetap terisi.
         */
        TetanggaKembar: {
            /** Iddesa */
            iddesa: string;
            /** Nmdesa */
            nmdesa: string | null;
            /** Nmkec */
            nmkec: string | null;
            /** Idkab */
            idkab: string | null;
            /** Nmkab */
            nmkab: string | null;
            /** Persen */
            persen: number;
        };
        /**
         * VarianJalurEkonomi
         * @description Varian jalur ekonomi yang didukung sebagai parameter path `varian`.
         * @enum {string}
         */
        VarianJalurEkonomi: "komoditas" | "gudang-kopdes" | "cold-storage" | "wisata";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    kesehatan_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status hidup API beserta versi dan tanggal data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_DataKesehatan_"];
                };
            };
        };
    };
    daftar_provinsi_api_wilayah_provinsi_get: {
        parameters: {
            query?: {
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar provinsi berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_Provinsi__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ringkasan_wilayah_api_wilayah_ringkasan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cacah provinsi, kabupaten, dan desa secara nasional */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_RingkasanWilayah_"];
                };
            };
        };
    };
    pusat_wilayah_api_wilayah_pusat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Titik pusat tiap provinsi dan kabupaten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_PusatWilayah_"];
                };
            };
        };
    };
    daftar_kabupaten_api_wilayah_kabupaten_get: {
        parameters: {
            query?: {
                prov?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar kabupaten berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_Kabupaten__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daftar_desa_api_wilayah_desa_get: {
        parameters: {
            query: {
                kab: string;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar desa satu kabupaten, berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_DesaRingkas__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cari_desa_api_desa_cari_get: {
        parameters: {
            query: {
                q: string;
                kab?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar desa yang cocok, berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_BarisIndeksKartu__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    kartu_detail_api_model_kartu__iddesa__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kode desa 10 digit */
                iddesa: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Satu Kartu Ekonomi Desa utuh */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_dict_str__Any__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daftar_peta_peran_api_model_peta_peran_get: {
        parameters: {
            query?: {
                /** @description Kode provinsi 2 digit */
                prov?: string | null;
                /** @description Kode kabupaten 4 digit */
                kab?: string | null;
                zona?: ("Zona Pemerintah" | "Zona Mitra" | "Zona Poros" | "Zona Bantuan" | "Belum Terpetakan") | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar baris ringkas Peta Peran, berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_dict_str__Any___"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ringkasan_peta_peran_api_model_peta_peran_ringkasan_get: {
        parameters: {
            query?: {
                /** @description Kode kabupaten 4 digit */
                kab?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan Peta Peran per kabupaten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_Any_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail_peta_peran_api_model_peta_peran__iddesa__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kode desa 10 digit */
                iddesa: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baris penuh Peta Peran satu desa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_dict_str__Any__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daftar_sel_api_model_citra_potensi_get: {
        parameters: {
            query?: {
                /** @description Filter provinsi (2 digit) */
                prov?: string | null;
                /** @description Filter target komoditas (persis) */
                target?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar metadata sel citra */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_dict_str__Any___"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail_sel_api_model_citra_potensi_sel_get: {
        parameters: {
            query: {
                /** @description Provinsi (2 digit), wajib */
                prov: string;
                /** @description Target, wajib */
                target: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata dan skor satu sel citra */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_dict_str__Any__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daftar_jalur_api_model_jalur_ekonomi__varian__get: {
        parameters: {
            query?: {
                /** @description Filter kabupaten (4 digit) */
                kab?: string | null;
                /** @description Filter desa (poros atau anggota), 10 digit */
                iddesa?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path: {
                varian: components["schemas"]["VarianJalurEkonomi"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar baris ringkas jalur ekonomi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_dict_str__Any___"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail_jalur_api_model_jalur_ekonomi__varian___id_jalur__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                varian: components["schemas"]["VarianJalurEkonomi"];
                id_jalur: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Satu grup jalur ekonomi utuh */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_dict_str__Any__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    desa_kembar_api_model_desa_kembar__iddesa__get: {
        parameters: {
            query?: {
                k?: number | null;
            };
            header?: never;
            path: {
                iddesa: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tetangga terdekat beserta persentase kemiripan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_DataDesaKembar_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    berita_desa_api_berita__iddesa__get: {
        parameters: {
            query?: {
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path: {
                iddesa: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar berita satu desa, berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_ItemBerita__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profil_saya_api_profil_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Id dan peran akun pemanggil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_ProfilSaya_"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanChat"];
            };
        };
        responses: {
            /** @description Jawaban Asisten Desa beserta jejak fungsinya */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_DataJawaban_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    segarkan_berita_api_admin_berita_segarkan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanSegarkan"];
            };
        };
        responses: {
            /** @description Tanda pekerjaan penyegaran sudah dimulai */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_TerimaSegarkan_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hapus_berita_api_admin_berita__id_berita__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_berita: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identitas berita yang terhapus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_BeritaTerhapus_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    daftar_pengguna_api_admin_pengguna_get: {
        parameters: {
            query?: {
                q?: string | null;
                /** @description Nomor halaman */
                hal?: number;
                /** @description Ukuran halaman */
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pengguna beserta perannya, berpaginasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_list_ItemPengguna__"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ubah_peran_api_admin_pengguna__id_pengguna__peran_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_pengguna: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanUbahPeran"];
            };
        };
        responses: {
            /** @description Peran baru pengguna itu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_PeranDiubah_"];
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    status_sistem_api_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan status sistem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Amplop_DataStatus_"];
                };
            };
        };
    };
    laporan_desa_api_laporan__iddesa__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kode desa 10 digit */
                iddesa: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas PDF laporan desa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    geo_desa_api_geo_desa__idkab__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idkab: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas GeoJSON batas desa, terkompresi gzip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Parameter atau badan permintaan tidak lolos validasi */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
